;************** AULA 01 - PROGRAMA PARA PISCAR LED *****************
	LIST   P=PIC16F628A
	RADIX DEC	
	#INCLUDE <P16F628A.INC>
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _BODEN_OFF & _LVP_OFF & _CP_OFF & _MCLRE_OFF & _DATA_CP_OFF 
	;ou __CONFIG H'3F10'

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
	CONTADOR1
	CONTADOR2
	ENDC			;FIM DO BLOCO DE MEMÓRIA		
	
	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
		
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0		;Faz virar 1
	CLRF TRISB			;todo por B vira saida
	BCF STATUS, RP0		;faz virar 0

REPETE
	BSF PORTB, 1		;acende led
	BCF PORTB, 1		;apaga led
	GOTO REPETE			;repete o repete


	END